# Generated by Django 4.2.1 on 2023-06-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regression", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bikedata",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="bikedata",
            name="predict_count",
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
