# Generated by Django 4.2.1 on 2023-06-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regression", "0002_bikedata_date_bikedata_predict_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bikedata",
            name="predict_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
