# Generated by Django 4.2.1 on 2023-06-11 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regression", "0003_alter_bikedata_predict_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bikedata",
            name="workingday",
            field=models.PositiveIntegerField(
                choices=[(0, "주말"), (1, "중")],
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
    ]
