# Generated by Django 4.2.1 on 2023-06-11 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regression", "0004_alter_bikedata_workingday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bikedata",
            name="season",
            field=models.PositiveIntegerField(
                choices=[(1, "봄"), (2, "여름"), (3, "가을"), (4, "겨울")],
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="bikedata",
            name="weather",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "맑음, 약간 구름 낀 흐림"),
                    (2, "안개, 또는 약간 흐림"),
                    (3, "가벼운 눈 또는 비"),
                    (4, "심한 눈 또는 비"),
                ],
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
    ]
