# Generated by Django 4.2.1 on 2023-06-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("regression", "0006_alter_bikedata_workingday"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bikedata",
            options={"ordering": ["-date"]},
        ),
    ]
