# Generated by Django 4.2.1 on 2023-06-18 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BikeDataExcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season",
                    models.PositiveIntegerField(
                        choices=[(1, "봄"), (2, "여름"), (3, "가을"), (4, "겨울")],
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "workingday",
                    models.PositiveIntegerField(
                        choices=[(0, "주말"), (1, "주중")],
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "weather",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "맑음, 약간 구름 낀 흐림"),
                            (2, "안개, 또는 약간 흐림"),
                            (3, "가벼운 눈 또는 비"),
                            (4, "심한 눈 또는 비"),
                        ],
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "month",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("predict_count", models.PositiveIntegerField(blank=True, null=True)),
                ("date", models.DateField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
